version: "3.8"

services:
  api:
    build: ./project
    command: uvicorn app.server:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./project:/usr/src/app
    ports:
      - 8004:8000
    environment:
      - ENVIRONMENT=dev
      - TESTING=False
      - DATABASE_URL=postgres://postgres:postgres@api-db:5432/brainiac_dev
      - DATABASE_TEST_URL=postgres://postgres:postgres@api-db:5432/brainiac_test
    depends_on:
      - api-db

  api-db:
    build:
      context: ./project/db
      dockerfile: Dockerfile
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
